# =====================================================================
# 1. GLOBAL & PERFORMANCE SETTINGS
# =====================================================================
# Remap the prefix to Ctrl+z
unbind C-b
set-option -g prefix C-x
bind-key C-x send-prefix

# Fix Escape key delay for Vim/Neovim users (drops from 500ms to 0)
set -s escape-time 0

# Increase scrollback history limit (default is only 2000 lines)
set -g history-limit 50000


# Use Vim keybindings in copy mode
setw -g mode-keys vi
# Bind 'v' to start selecting text
bind-key -T copy-mode-vi v send-keys -X begin-selection
# Bind 'y' to copy text (yank)
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# Fix terminal colors (Enables true color/24-bit color support)
set -g default-terminal "screen-256color"
set -ga terminal-overrides ",xterm-256color:Tc"

# Enable mouse support for resizing and selection
set -g mouse on

# Do not allow autorename
set-option -g allow-rename off

# Easy config reload with a confirmation message in the status bar
bind r source-file ~/.config/tmux/tmux.conf \; display-message "Config reloaded!"

# =====================================================================
# 2. WINDOWS & PANES CREATION
# =====================================================================
# Split windows using | and - while keeping the current folder path
unbind '"'
unbind %
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

# New window using Alt+Enter while keeping the current folder path
bind -n M-Enter new-window -c "#{pane_current_path}"

# =====================================================================
# 3. NAVIGATION (NO PREFIX REQUIRED)
# =====================================================================
# Navigate panes smoothly using Alt + h/j/k/l
bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R

# Next and previous window using Alt + n/p
bind -n M-n next-window
bind -n M-p previous-window

# =====================================================================
# 4. RESIZING (NO PREFIX REQUIRED)
# =====================================================================
# Explicitly use Alt + Shift + Arrow keys to resize panes by 5 cells
bind -n M-Left resize-pane -L 4
bind -n M-Right resize-pane -R 5
bind -n M-Up resize-pane -U 5
bind -n M-Down resize-pane -D 5
# Enable OSC 52 clipboard forwarding for remote Neovim yanks.
set -as terminal-features ",*:clipboard"
